name: Makefile CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'Testing/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'Testing/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Build Project
      run: make build
  
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Run Unit Tests For Project
      run: make test
